### ISSUE TITLE
Reproducing the results

### ISSUE THREAD

**Issue by lx704612715** [uwgraphics/CoRL2018Constraint#1]
Dear Mr Subramani, 

my name Xing, I am very interested in your paper "Inferring geometric constraints in human
demonstrations". I am trying to reproduce your results and use them in my PhD project. Would you mind providing a brief description of how to set up this repo, maybe a README file? It would be extremely helpful when you can provide some examples or some comments on the "test.py". It is hard for me to understand the outputs of the function "constraint_robust_lsq", and I could not find a description for that. In addition, I have not seen that force/torque signals are used to infer constraints in this repo, am I wrong? Thank you very much in advance!

Best, 

Xing

**Comment by gsubramani** [comment]
Hi Xing, 
I think you are having trouble setting up the repo because the symcymod submodule needs to be checked out before you can use it. Since it's a small module, I've just replaced the submodule link with the actual code. 
I also added a Dockerfile which will help you understand how to build the code and run it. 

This repo only contains code that determines the constraint equations required to compute kinematic and force/moment errors. 
See derive_constraint_equations.py for all the generalized constraint equations available. 

Thanks for your question, 
Guru

**Comment by gsubramani** [comment]
I'll add a few more comments to test.py explaining what it all is soon.

**Comment by lx704612715** [comment]
Thank you for your help Guru! I have successfully run your code on my workstation!
